In [1]:
import numpy as np

In [3]:
my_list = [5, 3, 10]
my_list

[5, 3, 10]

In [5]:
y = np.array(my_list)

In [7]:
y

array([ 5,  3, 10])

In [11]:
type(y)

numpy.ndarray

In [13]:
matrix = np.array([[1, 2], [3, 4]])

In [15]:
matrix

array([[1, 2],
       [3, 4]])

In [17]:
x = np.random.rand(10)
x

array([0.97929021, 0.41821304, 0.62512696, 0.40452251, 0.1098294 ,
       0.02820814, 0.93571105, 0.17566886, 0.45776321, 0.62668666])

In [19]:
x = np.random.rand(10, 10)
x

array([[0.64984196, 0.7013951 , 0.91322372, 0.21428956, 0.37442919,
        0.55777729, 0.17281144, 0.7973517 , 0.2536903 , 0.49643022],
       [0.09408809, 0.89832998, 0.70380114, 0.83618365, 0.23109022,
        0.00957273, 0.79695221, 0.75051833, 0.98287157, 0.06524249],
       [0.74735469, 0.27255804, 0.53792854, 0.07185901, 0.76045129,
        0.65215516, 0.95760027, 0.88619335, 0.3053471 , 0.42799516],
       [0.27138626, 0.39420004, 0.14740214, 0.71921127, 0.44772818,
        0.55205947, 0.75447693, 0.23718339, 0.63464497, 0.56509828],
       [0.8720213 , 0.96401697, 0.09788451, 0.43153453, 0.12672339,
        0.23811792, 0.68122701, 0.11598213, 0.56695643, 0.65794953],
       [0.44544694, 0.19937709, 0.29513943, 0.72438198, 0.40728663,
        0.24705769, 0.7699696 , 0.43771057, 0.00381042, 0.19846245],
       [0.20148109, 0.83547175, 0.75797057, 0.12160761, 0.49454194,
        0.64905863, 0.02868301, 0.02012435, 0.83400022, 0.99502311],
       [0.47722762, 0.82109849, 0.5568884

In [21]:
x = np.random.randn(10)
x

array([-1.65665512, -0.91749765,  0.14631008, -0.03162455, -0.15762275,
        0.51206915, -1.01426497, -0.80957308,  0.32752389, -1.62695506])

In [23]:
x = np.random.randint(1, 10)
x

9

In [25]:
x = np.random.randint(1, 100, 15)
x

array([57, 82, 81, 28, 59, 70, 21, 94, 27, 85, 91, 71, 56, 68, 38])

In [27]:
x = np.arange(1, 50)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [29]:
x = np.arange(1, 50, 5)
x

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [31]:
x = np.eye(5)
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
x = np.ones(15)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [37]:
x = np.ones((15, 15))
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.

In [39]:
x.shape

(15, 15)

In [41]:
x = np.zeros(50)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [43]:
y

array([ 5,  3, 10])

In [45]:
len(y)

3

In [49]:
y.shape

(3,)

In [51]:
matrix.shape

(2, 2)

In [53]:
matrix.dtype

dtype('int32')

In [55]:
y = np.array([3, 5, 7, 8])
y.reshape(2,2)

array([[3, 5],
       [7, 8]])

In [57]:
y.max()

8

In [59]:
y.min()

3

In [61]:
y.argmax()

3

In [63]:
y.argmin()

0

In [65]:
x = np.arange(1, 5)
x

array([1, 2, 3, 4])

In [67]:
y = np.arange(1, 5)
z = x+y
z

array([2, 4, 6, 8])

In [69]:
z = x**2
z

array([ 1,  4,  9, 16])

In [71]:
k = np.sqrt(z)
k

array([1., 2., 3., 4.])

In [73]:
z = np.exp(y)
z

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [75]:
x = np.random.randint(1, 10, 10)
x

array([2, 4, 1, 7, 6, 2, 7, 3, 8, 7])

In [77]:
x[3]

7

In [81]:
x[0:3]

array([2, 4, 1])

In [83]:
x[0:6] = 10
x

array([10, 10, 10, 10, 10, 10,  7,  3,  8,  7])

In [85]:
matrix = np.random.randint(1, 10, (5, 5))
matrix

array([[5, 5, 8, 2, 3],
       [4, 1, 9, 1, 5],
       [6, 4, 7, 2, 2],
       [8, 6, 6, 5, 4],
       [8, 4, 1, 5, 3]])

In [87]:
matrix[2]

array([6, 4, 7, 2, 2])

In [89]:
matrix[0][2]

8

In [91]:
mini_matrix = matrix[:3]
mini_matrix

array([[5, 5, 8, 2, 3],
       [4, 1, 9, 1, 5],
       [6, 4, 7, 2, 2]])

In [93]:
mini_matrix = matrix[2:]
mini_matrix

array([[6, 4, 7, 2, 2],
       [8, 6, 6, 5, 4],
       [8, 4, 1, 5, 3]])

In [95]:
mini_matrix = matrix[:, :2]
mini_matrix

array([[5, 5],
       [4, 1],
       [6, 4],
       [8, 6],
       [8, 4]])

In [97]:
mini_matrix = matrix[:, 2:]
mini_matrix

array([[8, 2, 3],
       [9, 1, 5],
       [7, 2, 2],
       [6, 5, 4],
       [1, 5, 3]])

In [99]:
array1=np.random.randint(100, size=(6,4))
array1

array([[31, 42, 25, 28],
       [58,  5, 20, 16],
       [16, 99, 71, 18],
       [64, 50, 67, 32],
       [96, 43,  1, 51],
       [12, 90, 12, 20]])

In [101]:
array1.shape

(6, 4)

In [103]:
array1[array1>50]

array([58, 99, 71, 64, 67, 96, 51, 90])

In [105]:
array1>50

array([[False, False, False, False],
       [ True, False, False, False],
       [False,  True,  True, False],
       [ True, False,  True, False],
       [ True, False, False,  True],
       [False,  True, False, False]])

In [109]:
array1[array1>=50]

array([58, 99, 71, 64, 50, 67, 96, 51, 90])

In [111]:
array1[array1==50]

array([50])

In [113]:
array1[array1!=50]

array([31, 42, 25, 28, 58,  5, 20, 16, 16, 99, 71, 18, 64, 67, 32, 96, 43,
        1, 51, 12, 90, 12, 20])

In [115]:
array1[(array1>=50) & (array1<=70)]

array([58, 64, 50, 67, 51])

In [117]:
array1[(array1>=50) | (array1<=40)]

array([31, 25, 28, 58,  5, 20, 16, 16, 99, 71, 18, 64, 50, 67, 32, 96,  1,
       51, 12, 90, 12, 20])

In [119]:
array2=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [121]:
array3=np.array([[2,5,6],[9,10,11],[5,6,9]])

In [123]:
np.concatenate([array2, array3])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  5,  6],
       [ 9, 10, 11],
       [ 5,  6,  9]])

In [127]:
array4=np.array([[4,10,13],[7,14,15],[10,16,18]])

In [129]:
np.concatenate([array2, array3, array4])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  5,  6],
       [ 9, 10, 11],
       [ 5,  6,  9],
       [ 4, 10, 13],
       [ 7, 14, 15],
       [10, 16, 18]])

In [131]:
narray1=np.array([15,16,17])
narray1

array([15, 16, 17])

In [133]:
narray2=np.array([[1,2,3],[4,5,6],[7,8,9]])
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [135]:
np.vstack([narray1, narray2])

array([[15, 16, 17],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [137]:
narray3=np.array([[15], [16], [47]])
narray3

array([[15],
       [16],
       [47]])

In [139]:
np.hstack([narray3,array2])

array([[15,  1,  2,  3],
       [16,  4,  5,  6],
       [47,  7,  8,  9]])

In [143]:
new_array=np.array([15,16,17,12,49,52,12,14,36])
len(new_array)

9

In [145]:
array5=np.random.randint(350, size=(10,9))
array5

array([[218, 323, 200,  13, 184, 138, 245, 296, 297],
       [263,  22, 276,  26,  80,  29, 280, 131, 153],
       [ 30, 198,  16, 243, 209, 197, 340, 258, 320],
       [142, 189,  97, 225, 310,  12,  61, 111,  29],
       [250, 242,  67, 178,  47, 123, 305,  82, 132],
       [ 14, 346, 315, 247, 253, 108, 311,  27, 227],
       [332,  62, 101, 143, 104, 167, 290,  91, 291],
       [213, 152,  49, 320, 302, 203,  11, 119, 197],
       [102, 200,  98,  79, 196,  37,  52, 237, 184],
       [ 52, 279,  53, 208, 272,  44, 144, 228, 196]])

In [147]:
array5 + 2

array([[220, 325, 202,  15, 186, 140, 247, 298, 299],
       [265,  24, 278,  28,  82,  31, 282, 133, 155],
       [ 32, 200,  18, 245, 211, 199, 342, 260, 322],
       [144, 191,  99, 227, 312,  14,  63, 113,  31],
       [252, 244,  69, 180,  49, 125, 307,  84, 134],
       [ 16, 348, 317, 249, 255, 110, 313,  29, 229],
       [334,  64, 103, 145, 106, 169, 292,  93, 293],
       [215, 154,  51, 322, 304, 205,  13, 121, 199],
       [104, 202, 100,  81, 198,  39,  54, 239, 186],
       [ 54, 281,  55, 210, 274,  46, 146, 230, 198]])

In [149]:
array5 - 2

array([[216, 321, 198,  11, 182, 136, 243, 294, 295],
       [261,  20, 274,  24,  78,  27, 278, 129, 151],
       [ 28, 196,  14, 241, 207, 195, 338, 256, 318],
       [140, 187,  95, 223, 308,  10,  59, 109,  27],
       [248, 240,  65, 176,  45, 121, 303,  80, 130],
       [ 12, 344, 313, 245, 251, 106, 309,  25, 225],
       [330,  60,  99, 141, 102, 165, 288,  89, 289],
       [211, 150,  47, 318, 300, 201,   9, 117, 195],
       [100, 198,  96,  77, 194,  35,  50, 235, 182],
       [ 50, 277,  51, 206, 270,  42, 142, 226, 194]])

In [151]:
array5 * 10

array([[2180, 3230, 2000,  130, 1840, 1380, 2450, 2960, 2970],
       [2630,  220, 2760,  260,  800,  290, 2800, 1310, 1530],
       [ 300, 1980,  160, 2430, 2090, 1970, 3400, 2580, 3200],
       [1420, 1890,  970, 2250, 3100,  120,  610, 1110,  290],
       [2500, 2420,  670, 1780,  470, 1230, 3050,  820, 1320],
       [ 140, 3460, 3150, 2470, 2530, 1080, 3110,  270, 2270],
       [3320,  620, 1010, 1430, 1040, 1670, 2900,  910, 2910],
       [2130, 1520,  490, 3200, 3020, 2030,  110, 1190, 1970],
       [1020, 2000,  980,  790, 1960,  370,  520, 2370, 1840],
       [ 520, 2790,  530, 2080, 2720,  440, 1440, 2280, 1960]])

In [153]:
array5[:,0] * 10

array([2180, 2630,  300, 1420, 2500,  140, 3320, 2130, 1020,  520])

In [155]:
np.add(array5,2)

array([[220, 325, 202,  15, 186, 140, 247, 298, 299],
       [265,  24, 278,  28,  82,  31, 282, 133, 155],
       [ 32, 200,  18, 245, 211, 199, 342, 260, 322],
       [144, 191,  99, 227, 312,  14,  63, 113,  31],
       [252, 244,  69, 180,  49, 125, 307,  84, 134],
       [ 16, 348, 317, 249, 255, 110, 313,  29, 229],
       [334,  64, 103, 145, 106, 169, 292,  93, 293],
       [215, 154,  51, 322, 304, 205,  13, 121, 199],
       [104, 202, 100,  81, 198,  39,  54, 239, 186],
       [ 54, 281,  55, 210, 274,  46, 146, 230, 198]])

In [157]:
np.subtract(array5,7)

array([[211, 316, 193,   6, 177, 131, 238, 289, 290],
       [256,  15, 269,  19,  73,  22, 273, 124, 146],
       [ 23, 191,   9, 236, 202, 190, 333, 251, 313],
       [135, 182,  90, 218, 303,   5,  54, 104,  22],
       [243, 235,  60, 171,  40, 116, 298,  75, 125],
       [  7, 339, 308, 240, 246, 101, 304,  20, 220],
       [325,  55,  94, 136,  97, 160, 283,  84, 284],
       [206, 145,  42, 313, 295, 196,   4, 112, 190],
       [ 95, 193,  91,  72, 189,  30,  45, 230, 177],
       [ 45, 272,  46, 201, 265,  37, 137, 221, 189]])

In [159]:
np.multiply(array5,10)

array([[2180, 3230, 2000,  130, 1840, 1380, 2450, 2960, 2970],
       [2630,  220, 2760,  260,  800,  290, 2800, 1310, 1530],
       [ 300, 1980,  160, 2430, 2090, 1970, 3400, 2580, 3200],
       [1420, 1890,  970, 2250, 3100,  120,  610, 1110,  290],
       [2500, 2420,  670, 1780,  470, 1230, 3050,  820, 1320],
       [ 140, 3460, 3150, 2470, 2530, 1080, 3110,  270, 2270],
       [3320,  620, 1010, 1430, 1040, 1670, 2900,  910, 2910],
       [2130, 1520,  490, 3200, 3020, 2030,  110, 1190, 1970],
       [1020, 2000,  980,  790, 1960,  370,  520, 2370, 1840],
       [ 520, 2790,  530, 2080, 2720,  440, 1440, 2280, 1960]])

In [163]:
np.divide(array5, 50)

array([[4.36, 6.46, 4.  , 0.26, 3.68, 2.76, 4.9 , 5.92, 5.94],
       [5.26, 0.44, 5.52, 0.52, 1.6 , 0.58, 5.6 , 2.62, 3.06],
       [0.6 , 3.96, 0.32, 4.86, 4.18, 3.94, 6.8 , 5.16, 6.4 ],
       [2.84, 3.78, 1.94, 4.5 , 6.2 , 0.24, 1.22, 2.22, 0.58],
       [5.  , 4.84, 1.34, 3.56, 0.94, 2.46, 6.1 , 1.64, 2.64],
       [0.28, 6.92, 6.3 , 4.94, 5.06, 2.16, 6.22, 0.54, 4.54],
       [6.64, 1.24, 2.02, 2.86, 2.08, 3.34, 5.8 , 1.82, 5.82],
       [4.26, 3.04, 0.98, 6.4 , 6.04, 4.06, 0.22, 2.38, 3.94],
       [2.04, 4.  , 1.96, 1.58, 3.92, 0.74, 1.04, 4.74, 3.68],
       [1.04, 5.58, 1.06, 4.16, 5.44, 0.88, 2.88, 4.56, 3.92]])

In [165]:
np.mean(array5)

169.36666666666667

In [167]:
array5.max()

346

In [169]:
array5.min()

11

In [173]:
matrix = np.random.randint(1,10, (5,5))
matrix

array([[2, 9, 6, 6, 9],
       [3, 5, 1, 5, 2],
       [3, 8, 5, 1, 7],
       [1, 8, 1, 6, 9],
       [9, 2, 3, 7, 1]])

In [175]:
new_matrix = matrix[matrix>3]
new_matrix

array([9, 6, 6, 9, 5, 5, 8, 5, 7, 8, 6, 9, 9, 7])

In [177]:
new_matrix = matrix[matrix%2==0]
new_matrix

array([2, 6, 6, 2, 8, 8, 6, 2])